### ISSUE TITLE
PDF submissions are opened in libreoffice

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#282]
In what appears to be a regression (see #266), PDF submissions are no longer viewable from the latest client code. Since `libreoffice` is now present in `sd-svs-disp`, PDF files are opened in LibreOffice, which is a terrible user experience.

First, let's make sure we have a reliable reproduction of the issue. If so, we should consider fine-tuning the mimetype prefers to prioritize a different application for PDFs, same as we used before the introduction of LibreOffice in #266.

**Comment by emkll** [comment]
I can reliably reproduce this on latest `master`

**Comment by eloquence** [comment]
I am seeing this again, at least since the Buster transition w/ December 6 nightlies on Qubes.

**Comment by conorsch** [comment]
Likely resolved via #385, marking "needs reproducing." We can close if a test on latest master doesn't show the issue.

**Comment by eloquence** [comment]
![Screenshot_2020-01-22_16-56-37](https://user-images.githubusercontent.com/213636/72947850-46973900-3d38-11ea-81c6-5e906892b664.png)

Unfortunately this regression is indeed still present in latest nightlies.

**Comment by eloquence** [comment]
Per https://github.com/freedomofpress/securedrop-debian-packaging/pull/119 `securedrop-workstation-svs-disp` should be at `0.1.5+buster`, but the latest build I see on `apt-test-qubes` is `0.1.3+buster`. Are we just missing a release of this package?

**Comment by redshiftzero** [comment]
good find, we do not have a nightly build job for `securedrop-workstation-svs-disp`, we should add it and confirm that this issue is resolved in the latest build

**Comment by conorsch** [comment]
Partial implementation over in https://github.com/freedomofpress/securedrop-debian-packaging/pull/131 Confirmed that current behavior on SDW master was still opening PDFs in LibreOffice. After ([accidentally](https://github.com/freedomofpress/securedrop-debian-packaging/pull/131#issuecomment-577472386)) [publishing an updated `securedrop-workstation-svs-disp`](https://github.com/freedomofpress/securedrop-dev-packages-lfs/commit/43dd60f3bf6e79f57ec5c8609cbb86e0a3e3dc31), can confirm that the fixes in https://github.com/freedomofpress/securedrop-debian-packaging/pull/119 were sufficient: a `make all` resolves the issue, and PDFs are now opening in Evince as expected.

**Comment by eloquence** [comment]
I manually upgraded the package in the template, restarted `sd-viewer` and the template, and that also resolved it for me :tada:

**Comment by eloquence** [comment]
Is any follow-up action required on this issue?

**Comment by eloquence** [comment]
This is most likely fixed, but I'll re-test before closing.

**Comment by conorsch** [comment]
Thanks for nudge, @eloquence ; I've tested frequently recently, and can confirm that PDFs are opened in evince again, as we'd expect.
